# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def shared_pods
    swift_version = "3.0"
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'GoogleAPIClientForREST/Calendar'
    pod 'AppAuth', '~> 0.9.0'
    pod 'PromiseKit', '~> 4.0'
    pod 'RealmSwift', '~> 2.5.1'
    pod 'SwiftDate', '~> 4.0'
    pod 'Swinject', '~> 2.0.0'
end

target 'DatingCalTests' do
shared_pods
end

target 'DatingCal' do
    shared_pods

    swift_version = "3.0"
    pod 'ReachabilitySwift', '~> 3'
    pod 'ChameleonFramework'
    pod 'SVProgressHUD'
    pod 'TextFieldEffects'
    pod 'YYKit'
    pod 'FSCalendar'
    pod 'DZNEmptyDataSet'
    pod 'DateTimePicker'
    pod 'expanding-collection', '~> 1.0.3'

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '3.0'
        end
      end
    end
end
