# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'DatingCal' do

pod 'Alamofire'
pod 'ChameleonFramework'
pod 'SVProgressHUD'
pod 'SwiftyJSON'
pod 'TextFieldEffects'
pod 'YYKit'
pod 'FSCalendar'
pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'
pod 'Google/SignIn'
pod 'GoogleAPIClientForREST'

end
